# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'TesseractOCRiOS', '4.0.0'
pod 'GPUImage', '0.1.7'
target 'testCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testCamera

  target 'testCamera-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
