# Generated by Django 2.1.4 on 2019-01-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('qty', models.PositiveSmallIntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
