# Generated by Django 2.1.4 on 2019-02-07 16:06

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.CharField(max_length=10)),
                ('date_added', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=api.models.recieptsFile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
