# Generated by Django 2.1.4 on 2019-02-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190212_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='recipe_url',
        ),
    ]
