# Generated by Django 2.1.5 on 2019-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190219_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPCDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
