# Generated by Django 2.1.5 on 2019-03-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_upcdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='liked_recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Recipe'),
        ),
    ]
