# Generated by Django 2.1.5 on 2019-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_puser_liked_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puser',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='puser',
            name='liked_recipes',
            field=models.ManyToManyField(to='api.Recipe'),
        ),
    ]
